### ISSUE TITLE
[Refactor] 회원가입 페이지 로직 수정

### ISSUE THREAD

**Issue by jinsu4755** [team-nutee/NUTEE-Android#38]
- [x] 기존 형식을 fragment 형식으로 나누기

- [x] 각 fragment의 이벤트를 Activity로 분리하기

- [x] 각 fragment마다 에니메이션 새로 도입하기.
