### ISSUE TITLE
[Refactor] 디테일 페이지 수정

### ISSUE THREAD

**Issue by jinsu4755** [team-nutee/NUTEE-Android#51]
### 현제 디테일 페이지
1. Fragment로 띄워지고 있으며 의존성이 여기저기...

---
### 바꿀 예정

- [ ] 바뀐 디자인에 따라 Activity로 다시 만들기.

- [ ] 신고, 수정을 보여주는 Dialog 생성자 수정.

- [ ] 사진 보여주는 화면 여러개를 만들지 않고 그냥  하나의 뷰에서 match_constraint로 처리하기.
